### ISSUE TITLE
Latest version (the new branch version) crash

### ISSUE THREAD

**Issue by CsharpNoobDude** [Nostrademous/Dota2-FullOverwrite#166]
I set up a local lobby, both bot-teams are set to local dev script (and filled of course).
I start the match, they select their heroes correctly, but after that game starting banner (each hero is shown in that pose, and that drumming sound is playing). And then - crash.
ByByurton has that issue too, so it is not only me.

**Comment by Nostrademous** [comment]
Can you set "Dire" side to "default (not local dev script) and see what happens please?

**Comment by CsharpNoobDude** [comment]
Yeah, will do. (Well, later, need to do stuff, I can do that in 5 hours)

**Comment by ByBurton** [comment]
I tested around, and no matter what I tried (reinstalling dota, dire valve bots and radiant these, vise versa, etc. etc) nothing helped.

**Comment by Nostrademous** [comment]
I merged the branches... can you try again now as Radiant.

**Comment by ByBurton** [comment]
Sure, I will.

**Comment by ByBurton** [comment]
NOPE, still not. FFS. 
I FUCKING REINSTALLED THE GAME. I GOT THE LATEST VERSION! IT HAS TO FUCKING RUN!

**Comment by Nostrademous** [comment]
let me wipe my repo, reboot, pull a fresh copy, and see...

**Comment by Nostrademous** [comment]
okay... I did all that and no issues.

I deleted my bots locally on my computer, wiped the git repo, rebooted, re-added my SSH key to git (it gets deleted when I wipe my repo locally), followed the wiki instructions (made a new bots/ and did a fresh clone into it), opened dota 2, loaded a lobby game with Local Dev Scripts for Radiant, played...

**Comment by ByBurton** [comment]
http://imgur.com/a/aasM2

**Comment by Nostrademous** [comment]
have you tried deleting the "bots" directory and and doing a fresh git clone?

**Comment by ByBurton** [comment]
Yes, of course. Could you not see? All files were there.
Was the directory correct? I mean it has to be, they showed up in the DotA 2 lobby system and picked their assigned heroes. Would you like to add me on steam? So I can stream my screen to you?

**Comment by Nostrademous** [comment]
also, I run with the following launch options "-novid -console -condebug"

if you run with those and it crashes it should have a dump located at:
C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota

with names like:
console.<NUMBER>.log

**Comment by ByBurton** [comment]
http://steamcommunity.com/id/LdyRoseBlood/
Will try to look at te log now.

**Comment by ByBurton** [comment]
NOPE, nope still crashes.

**Comment by ByBurton** [comment]
http://collabedit.com/x725s

**Comment by ByBurton** [comment]
Do I have to start steam as administrator?

**Comment by Nostrademous** [comment]
diagnosing the error she showed me it looks like for whatever reason her dota2 install is missing the:
vscripts/game directory which included botsinit.lua, gameinit.lua, and dkjson.lua
that directory was part of a Valve patch on Feb 15, 2017.

I have no idea why it wouldn't have patched for her...

**Comment by Nostrademous** [comment]
she re-validated her Dota 2 install and it added 13 missing files... works now.

**Comment by ByBurton** [comment]
What about the C# dude?
