### ISSUE TITLE
Bots not initializing when playing with a human

### ISSUE THREAD

**Issue by pbenologa** [Nostrademous/Dota2-FullOverwrite#92]
I tweaked my own version of hero selection to be dynamic when there is a human player but it seems the bots are not initializing and they are just stuck on the base with no items. 

http://m.imgur.com/UI0oyG6?r for reference.

**Comment by Nostrademous** [comment]
ok... stuff need to be tweaked. When playing with human the offsets for slot position are different.

**Comment by Nostrademous** [comment]
Check this - probably much better than our hero_selection.lua implementation. Contributor is eriKKo

local pickForPlayers = false
local heroes = {
  [TEAM_RADIANT] = {
    {"npc_dota_hero_nevermore", LANE_MID},
    {"npc_dota_hero_viper", LANE_TOP},
    {"npc_dota_hero_sven", LANE_BOT},
    {"npc_dota_hero_lion", LANE_BOT},
    {"npc_dota_hero_windrunner", LANE_TOP}
  },
  [TEAM_DIRE] = {
    {"npc_dota_hero_nevermore", LANE_MID},
    {"npc_dota_hero_lina", LANE_BOT},
    {"npc_dota_hero_earthshaker", LANE_TOP},
    {"npc_dota_hero_mirana", LANE_TOP},
    {"npc_dota_hero_juggernaut", LANE_BOT}
  }
}

function UpdateLaneAssignments()
  local lanes = {}
  for i,hero in ipairs(heroes[GetTeam()]) do
    lanes[i] = hero[2]
  end
  return lanes
end

function Think()
  function f()
    for i,player in ipairs(GetTeamPlayers(GetTeam())) do
      if pickForPlayers or IsPlayerBot(player) then
        SelectHero(player, heroes[GetTeam()][i][1])
      end
    end
  end
  local status, err = pcall(f)
  if not status then
    print(err)
  end
end

**Comment by Nostrademous** [comment]
obviously change the hero names to the ones we have implemented

**Comment by pbenologa** [comment]
I used the code you provided but the problem still exists. Upon checking the codes it seems like the initiation takes place on GAME_STATE_TEAM_SHOWCASE, I changed it to GAME_STATE_PRE_GAME and it work. 

> function X:Think(bot)
    if ( GetGameState() == GAME_STATE_PRE_GAME ) then
        if not self.Init then
            self:DoInit(bot)
        end
    end

**Comment by pbenologa** [comment]
So far my workaround is working so ill close this now.

**Comment by Nostrademous** [comment]
Did you do a PR for it? We should fix our hero selection to work with humans or full bot teams.

**Comment by Nostrademous** [comment]
If you are not getting other console bugs it's all good

**Comment by pbenologa** [comment]
Im currently using the code you gave and it works fine. My main concern was fixed when I changed the game state where the bots initialized, from GAME_STATE_TEAM_SHOWCASE to GAME_STATE_PRE_GAME though i'm not sure if that change is good for bots vs bots game thats why i never made a PR yet.

**Comment by Nostrademous** [comment]
can you check if anything errors when you do an all bot-vs-bot please? I moved init there on purpose b/c I was seeing a weird error with item purchasing failing to initialize properly if I didn't. But we can technically fix that a different way.

**Comment by pbenologa** [comment]
Will do so later. I'll update this after testing.

**Comment by Nostrademous** [comment]
you checked in the change to move init to GAME_STATE_PRE_GAME but not the updated hero_selection, FYI

**Comment by pbenologa** [comment]
Ah yes. I'll try to make a much better hero_selection where you can set a team then the other team's lineup would be random. I'll work on this today.

**Comment by Nostrademous** [comment]
Don't waste too much time on it. My plan is to eventually use a counter picking strategy once we have all the heroes implemented.

**Comment by pbenologa** [comment]
Oh okay. 👍

**Comment by Nostrademous** [comment]
This should work now (I Hope)
